### ISSUE TITLE
Issue with log

### ISSUE THREAD

**Issue by Toshibass** [neuralassembly/raspi#1]
I notice there's a big down side to using  "startup script of WebIOPi for Jessie"  and running   sudo systemctl start webiopi  or  sudo systemctl enable webiopi  in that although the log file /usr/log/webiopi gets populated as usual also usr/log/syslog gets every instruction that webiopi makes (not just debug and info calls **every call**) at some points I am getting over 100 writes to this syslog in 1 second is there anyway to stop this happening ?

**Comment by neuralassembly** [comment]
I stopped logging to /var/log/syslog by adding "StandardOutput=null" to webiopi.service. Does this modification solve your problem?

**Comment by Toshibass** [comment]
Yes thats solved the extra logging issue thanks
